name       : ne
version    : 3.2.1
release    : 5
source     :
    - https://github.com/vigna/ne/archive/3.2.1.tar.gz : 6b9324d9a4c3deef02f4ecf75407f5b5ed4e68a3bb4af3f9c1ea19dc628f9b5d
homepage   : http://ne.di.unimi.it/
license    : GPL-3.0-or-later
component  : editor
summary    : ne, the nice editor
description: |
    ne, the nice editor. ne is a free (GPL'd) text editor based on the POSIX standard.
builddeps  :
    - pkgconfig(ncursesw)
    - texinfo
setup      : |
    sed -i 's:CC=c99:CC=gcc:g' src/makefile
build      : |
    %make build PREFIX=/usr
    cd $workdir
    %make docs
install    : |
    %make_install PREFIX=/usr
    rm -f $installdir/usr/share/doc/ne/{CHANGES,COPYING,NEWS,README.md}
