name       : ne
version    : 3.0.1
release    : 1
source     :
    - https://github.com/vigna/ne/archive/3.0.1.tar.gz : e7c98799c348bc9fb3c8cda29f1d3248213c33343cbe0b21bcb4199abc3eb2a4
license    : GPL-3.0
component  : editor
summary    : ne is a free (GPL'd) text editor
description: |
    ne is a free (GPL'd) text editor
builddeps  :
    - texlive
setup      : |
    %patch -p1 < $pkgfiles/Enable_doc_installation.patch
    sed -i 's:CC=c99:CC=gcc:g' src/makefile
build      : |
    %make build PREFIX=/usr
    cd $workdir
    %make docs
install    : |
    %make_install PREFIX=/usr
