name       : ne
version    : 3.1.1
release    : 3
source     :
    - https://github.com/vigna/ne/archive/3.1.1.tar.gz : a88a24153a17844bb2dfbc3c76a6fbd1d456ee0e8215d5139551cf082627596a
license    : GPL-3.0
component  : editor
summary    : ne is a free (GPL'd) text editor
description: |
    ne is a free (GPL'd) text editor
builddeps  :
    - texlive
setup      : |
    sed -i 's:CC=c99:CC=gcc:g' src/makefile
build      : |
    %make build PREFIX=/usr
    cd $workdir
    %make docs
install    : |
    %make_install PREFIX=/usr
