name       : ne
version    : 3.1.2
release    : 4
source     :
    - https://github.com/vigna/ne/archive/3.1.2.tar.gz : bdf09a377660527857bd25217fc91505ae2b19c41590f8a25efc91aef785a3e2
license    : GPL-3.0
component  : editor
summary    : ne is a free (GPL'd) text editor
description: |
    ne is a free (GPL'd) text editor
builddeps  :
    - texlive
setup      : |
    sed -i 's:CC=c99:CC=gcc:g' src/makefile
build      : |
    %make build PREFIX=/usr
    cd $workdir
    %make docs
install    : |
    %make_install PREFIX=/usr
