name       : ne
version    : 3.3.1
release    : 8
source     :
    - https://github.com/vigna/ne/archive/refs/tags/3.3.1.tar.gz : 931f01380b48e539b06d65d80ddf313cce67aab6d7b62462a548253ab9b3e10a
homepage   : http://ne.di.unimi.it/
license    : GPL-3.0-or-later
component  : editor
summary    : ne, the nice editor
description: |
    ne, the nice editor. ne is a free (GPL'd) text editor based on the POSIX standard.
builddeps  :
    - pkgconfig(ncursesw)
    - texinfo
setup      : |
    sed -i 's:CC=c99:CC=gcc:g' src/makefile
build      : |
    %make build PREFIX=/usr
    cd $workdir
    %make docs
install    : |
    %make_install PREFIX=/usr
    rm -f $installdir/usr/share/doc/ne/{CHANGES,COPYING,NEWS,README.md}
