name       : ne
version    : 3.1.0
release    : 2
source     :
    - https://github.com/vigna/ne/archive/3.1.0.tar.gz : 3926d9d74ad8c482f5daca9a81a05aaf2cac11329b2d2bf40bd392fdf06b4568
license    : GPL-3.0
component  : editor
summary    : ne is a free (GPL'd) text editor
description: |
    ne is a free (GPL'd) text editor
builddeps  :
    - texlive
setup      : |
    sed -i 's:CC=c99:CC=gcc:g' src/makefile
build      : |
    %make build PREFIX=/usr
    cd $workdir
    %make docs
install    : |
    %make_install PREFIX=/usr
